language: node_js
sudo: required
dist: trusty
node_js:
  - '10'
addons:
  firefox: latest
  chrome: stable
cache:
  directories:
  - node_modules
script:
- xvfb-run npm run test -- -l chrome
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then wct -s 'windows 10/microsoftedge@17' -s 'windows 10/microsoftedge@18' -s 'windows 8.1/internet explorer@11' -s 'os x 10.11/safari@9' -s 'os x 10.12/safari@10' -s 'macos 10.13/safari@11' -s 'macos 10.14/safari@12' -s 'Linux/chrome@41' -s 'Linux/firefox@62' -s 'Linux/firefox@63'; fi
